/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * KITCC Library API
 * OpenAPI spec version: 1.0.0
 */
import type { Error } from './error';

/**
 * リクエストの構文が誤っている
 */
export type BadRequestResponse = Error;
