/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * KITCC Library API
 * OpenAPI spec version: 1.0.0
 */

export type CreateBookBody = {
  authors: string[];
  description: string;
  /** @pattern ^\d{10}(\d{3})?$ */
  isbn: string;
  publishedDate: string;
  publisher: string;
  stock: number;
  thumbnail?: string;
  title: string;
};
