/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * KITCC Library API
 * OpenAPI spec version: 1.0.0
 */

export type GetBooksSort = typeof GetBooksSort[keyof typeof GetBooksSort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetBooksSort = {
  NUMBER_0: '0',
  NUMBER_1: '1',
  NUMBER_2: '2',
  NUMBER_3: '3',
} as const;
