/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * KITCC Library API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBooksSort } from './getBooksSort';

export type GetBooksParams = {
/**
 * ページ番号
 */
page?: string;
/**
 * 1ページあたりの表示数
 */
limit?: string;
/**
 * タイトル
 */
title?: string;
/**
 * 著者
 */
author?: string;
/**
 * 出版社
 */
publisher?: string;
/**
 * ISBN
 */
isbn?: string;
/**
 * ソート順 1: id昇順 2: id降順 3: 出版日昇順 4: 出版日降順

 */
sort?: GetBooksSort;
};
