/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * KITCC Library API
 * OpenAPI spec version: 1.0.0
 */
import type { Book } from './book';

export type GetBooks200 = {
  books: Book[];
  /** 総書籍数 */
  totalBook: number;
};
