/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * KITCC Library API
 * OpenAPI spec version: 1.0.0
 */
import type { GetLoansSort } from './getLoansSort';

export type GetLoansParams = {
/**
 * 貸出履歴を取得するユーザーのID
 */
userId?: string;
/**
 * 貸出履歴を取得する書籍のID
 */
bookId?: string;
/**
 * ページ番号
 */
page?: string;
/**
 * 1ページあたりの表示数
 */
limit?: string;
/**
 * ソート順
 */
sort?: GetLoansSort;
};
