/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * KITCC Library API
 * OpenAPI spec version: 1.0.0
 */

export type GetLoansSort = typeof GetLoansSort[keyof typeof GetLoansSort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetLoansSort = {
  NUMBER_0: '0',
  NUMBER_1: '1',
  NUMBER_2: '2',
  NUMBER_3: '3',
  NUMBER_4: '4',
  NUMBER_5: '5',
} as const;
