/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * KITCC Library API
 * OpenAPI spec version: 1.0.0
 */
import type { GetLoans200LoansItem } from './getLoans200LoansItem';

export type GetLoans200 = {
  loans: GetLoans200LoansItem[];
  totalLoan: number;
};
