/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * KITCC Library API
 * OpenAPI spec version: 1.0.0
 */
import type { Book } from './book';
import type { Loan } from './loan';
import type { User } from './user';

export type GetLoans200LoansItem = {
  books?: Book;
  loans?: Loan;
  users?: User;
};
