/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * KITCC Library API
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';

export type GetUsers200 = {
  /** 総ユーザー数 */
  totalUser: number;
  users: User[];
};
