/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * KITCC Library API
 * OpenAPI spec version: 1.0.0
 */

export type GetUsersParams = {
/**
 * ページ番号
 */
page?: string;
/**
 * 1ページあたりの表示数
 */
limit?: string;
/**
 * ユーザー名
 */
name?: string;
/**
 * メールアドレス
 */
email?: string;
};
