/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * KITCC Library API
 * OpenAPI spec version: 1.0.0
 */
import type { Error } from './error';

/**
 * サーバ内部でエラーが発生した
 */
export type InternalServerErrorResponse = Error;
