/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * KITCC Library API
 * OpenAPI spec version: 1.0.0
 */

export interface Loan {
  bookId: number;
  /** レコードが作成されたUNIX時間 */
  createdAt?: number;
  /** レコードが最後に更新されたUNIX時間 */
  updatedAt?: number;
  userId: number;
  volume: number;
}
