/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * KITCC Library API
 * OpenAPI spec version: 1.0.0
 */
import type { Error } from './error';

/**
 * 指定されたリソースが存在しない
 */
export type NotFoundResponse = Error;
