/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * KITCC Library API
 * OpenAPI spec version: 1.0.0
 */
import type { SearchBooks200BooksItem } from './searchBooks200BooksItem';

export type SearchBooks200 = {
  books: SearchBooks200BooksItem[];
  /** 総書籍数 */
  totalBook: number;
};
