/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * KITCC Library API
 * OpenAPI spec version: 1.0.0
 */
import type { GoogleBook } from './searchBooks200BooksItem';

export type SearchBooks200 = {
	books: GoogleBook[];
	/** 総書籍数 */
	totalBook: number;
};
