/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * KITCC Library API
 * OpenAPI spec version: 1.0.0
 */

export type SearchGoogleBooks200BooksItem = {
  authors: string[];
  description?: string;
  id: string;
  isbn?: string;
  publishedDate?: string;
  publisher?: string;
  thumbnail?: string;
  title: string;
};
