/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * KITCC Library API
 * OpenAPI spec version: 1.0.0
 */
import type { Error } from './error';

/**
 * 適切な認証情報を持たずにリソースにアクセスしようとした
 */
export type UnauthorizedResponse = Error;
