/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * KITCC Library API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 貸出数が在庫数を超えているリクエスト
 */
export type UpsertLoans409 = {
  bookId: number;
  userId: number;
  volume: number;
};
