/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * KITCC Library API
 * OpenAPI spec version: 1.0.0
 */

export type UpsertLoansBodyItem = {
  bookId: number;
  userId: number;
  volume: number;
};
