/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * KITCC Library API
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  email: string;
  id: number;
  name: string;
  /** @nullable */
  sessionToken?: string | null;
}
