/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * KITCC Library API
 * OpenAPI spec version: 1.0.0
 */
export type Logout200 = {
  message?: string;
};

export type LoginBody = {
  email: string;
  /**
   * @minLength 8
   * @pattern ^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]+$
   */
  password: string;
};

/**
 * 貸出数が在庫数を超えているリクエスト
 */
export type UpsertLoans409 = {
  bookId: number;
  userId: number;
  volume: number;
};

export type UpsertLoans404 = {
  bookId: number;
  userId: number;
};

export type UpsertLoansBodyItem = {
  bookId: number;
  userId: number;
  volume: number;
};

export type GetLoans200 = {
  loans: Loan[];
  totalPage: number;
};

export type GetLoansParams = {
/**
 * 貸出履歴を取得するユーザーのID
 */
userId?: string;
/**
 * 貸出履歴を取得する書籍のID
 */
bookId?: string;
/**
 * ページ番号
 */
page?: string;
/**
 * 1ページあたりの表示数
 */
limit?: string;
};

export type DeleteUser204 = {
  message?: string;
};

export type UpdateUserBody = {
  email?: string;
  name?: string;
  /**
   * @minLength 8
   * @pattern ^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]+$
   */
  password?: string;
};

export type CreateUserBody = {
  email: string;
  name: string;
  /**
   * @minLength 8
   * @pattern ^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]+$
   */
  password: string;
};

export type GetUsers200 = {
  totalPage: number;
  users: User[];
};

export type GetUsersParams = {
/**
 * ページ番号
 */
page?: string;
/**
 * 1ページあたりの表示数
 */
limit?: string;
/**
 * ユーザー名
 */
name?: string;
/**
 * メールアドレス
 */
email?: string;
};

export type SearchBooks200BooksItem = {
  authors: string[];
  isbn?: string;
  publisher?: string;
  thumbnail?: string;
  title: string;
};

export type SearchBooks200 = {
  books: SearchBooks200BooksItem[];
  /** 総ページ数 */
  totalPage: number;
};

export type SearchBooksParams = {
/**
 * ページ番号
 */
page?: string;
/**
 * 1ページあたりの表示数
 */
limit?: string;
/**
 * タイトル
 */
intitle?: string;
/**
 * 著者
 */
inauthor?: string;
/**
 * 出版社
 */
inpublisher?: string;
/**
 * ISBN
 */
isbn?: string;
};

export type UpdateBookBody = {
  authors?: string[];
  /** @pattern ^\d{10}(\d{3})?$ */
  isbn?: string;
  publisher?: string;
  stock?: number;
  title?: string;
};

export type CreateBookBody = {
  authors: string[];
  /** @pattern ^\d{10}(\d{3})?$ */
  isbn: string;
  publisher: string;
  stock: number;
  thumbnail?: string;
  title: string;
};

export type GetBooks200 = {
  books: Book[];
  /** 総ページ数 */
  totalPage: number;
};

export type GetBooksParams = {
/**
 * ページ番号
 */
page?: string;
/**
 * 1ページあたりの表示数
 */
limit?: string;
/**
 * タイトル
 */
title?: string;
/**
 * 著者
 */
author?: string;
/**
 * 出版社
 */
publisher?: string;
/**
 * ISBN
 */
isbn?: string;
};

/**
 * 指定されたリソースが存在しない
 */
export type NotFoundResponse = Error;

/**
 * 適切な認証情報を持たずにリソースにアクセスしようとした
 */
export type UnauthorizedResponse = Error;

/**
 * サーバ内部でエラーが発生した
 */
export type InternalServerErrorResponse = Error;

/**
 * リクエストの構文が誤っている
 */
export type BadRequestResponse = Error;

export interface Loan {
  bookId: number;
  /** レコードが作成されたUNIX時間 */
  createdAt?: number;
  /** レコードが最後に更新されたUNIX時間 */
  updatedAt?: number;
  userId: number;
  volume: number;
}

export interface User {
  email: string;
  id: number;
  name: string;
  /** @nullable */
  sessionToken?: string | null;
}

export interface Error {
  message: string;
}

export interface Book {
  authors: string[];
  id: number;
  /** @pattern ^\d{10}(\d{3})?$ */
  isbn: string;
  publisher: string;
  stock: number;
  thumbnail?: string;
  title: string;
}

