openapi: 3.0.3
info:
  title: KITCC Library API
  contact:
    name: KITCC
    url: "https://www.kitcc.org/"
    email: "question@kitcc.org"
  license: 
    name: MIT
    url: https://en.wikipedia.org/wiki/MIT_License
  version: "1.0.0"

servers:
  - url: "https://kitcc-library.kitcc.workers.dev"

tags:
  - name: book
    description: 書籍に関するAPI
  - name: user
    description: ユーザーに関するAPI
  - name: loan
    description: 貸借に関するAPI

paths:
  /books:
    $ref: "./paths/book.yml#/books"
  /books/{bookId}:
    $ref: "./paths/book.yml#/book"

  # /users:
  # /users/{userId}:

  # /loans:
  # /loans/{loanId}:

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  
  schemas:
    Book: 
      $ref: "./components/schemas/book.yml"
