name: Validate API Specification

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install redocly-cli
        run: |
          npm install @redocly/cli -g

      - name: Validate API Specification
        run: |
          redocly lint ./api/openapi.yml
